/**
 * Brave-specific helpers.
 *
 * Brave Web Search has a `search_lang` query parameter (default: `en`).
 * To avoid an implicit English bias for non-English queries, we can infer
 * `search_lang` from the query language (franc ISO-639-3) when possible.
 */

export const BRAVE_SEARCH_LANGS = [
  "ar",
  "eu",
  "bn",
  "bg",
  "ca",
  "zh-hans",
  "zh-hant",
  "hr",
  "cs",
  "da",
  "nl",
  "en",
  "en-gb",
  "et",
  "fi",
  "fr",
  "gl",
  "de",
  "el",
  "gu",
  "he",
  "hi",
  "hu",
  "is",
  "it",
  "jp",
  "kn",
  "ko",
  "lv",
  "lt",
  "ms",
  "ml",
  "mr",
  "nb",
  "pl",
  "pt-br",
  "pt-pt",
  "pa",
  "ro",
  "ru",
  "sr",
  "sk",
  "sl",
  "es",
  "sv",
  "ta",
  "te",
  "th",
  "tr",
  "uk",
  "vi",
] as const;

export type BraveSearchLang = (typeof BRAVE_SEARCH_LANGS)[number];

export const BRAVE_SEARCH_LANG_SET = new Set<string>(BRAVE_SEARCH_LANGS as readonly string[]);

export function isBraveSearchLang(v: string): v is BraveSearchLang {
  return BRAVE_SEARCH_LANG_SET.has(v);
}

export const BRAVE_SEARCH_LANG_NAME_BY_CODE = {
  ar: "Arabic",
  eu: "Basque",
  bn: "Bengali",
  bg: "Bulgarian",
  ca: "Catalan",
  "zh-hans": "Chinese (Simplified)",
  "zh-hant": "Chinese (Traditional)",
  hr: "Croatian",
  cs: "Czech",
  da: "Danish",
  nl: "Dutch",
  en: "English",
  "en-gb": "English (UK)",
  et: "Estonian",
  fi: "Finnish",
  fr: "French",
  gl: "Galician",
  de: "German",
  el: "Greek",
  gu: "Gujarati",
  he: "Hebrew",
  hi: "Hindi",
  hu: "Hungarian",
  is: "Icelandic",
  it: "Italian",
  jp: "Japanese",
  kn: "Kannada",
  ko: "Korean",
  lv: "Latvian",
  lt: "Lithuanian",
  ms: "Malay",
  ml: "Malayalam",
  mr: "Marathi",
  nb: "Norwegian Bokmal",
  pl: "Polish",
  "pt-br": "Portuguese (Brazil)",
  "pt-pt": "Portuguese (Portugal)",
  pa: "Punjabi",
  ro: "Romanian",
  ru: "Russian",
  sr: "Serbian",
  sk: "Slovak",
  sl: "Slovenian",
  es: "Spanish",
  sv: "Swedish",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tr: "Turkish",
  uk: "Ukrainian",
  vi: "Vietnamese",
} as const satisfies Record<BraveSearchLang, string>;

// franc-min returns ISO-639-3 codes; Brave expects a smaller, fixed enum.
const FRANC_TO_BRAVE_SEARCH_LANG: Record<string, BraveSearchLang> = {
  ara: "ar",
  eus: "eu",
  ben: "bn",
  bul: "bg",
  cat: "ca",
  cmn: "zh-hans",
  zho: "zh-hans",
  yue: "zh-hant",
  hrv: "hr",
  ces: "cs",
  dan: "da",
  nld: "nl",
  eng: "en",
  est: "et",
  fin: "fi",
  fra: "fr",
  glg: "gl",
  deu: "de",
  ell: "el",
  guj: "gu",
  heb: "he",
  hin: "hi",
  hun: "hu",
  isl: "is",
  ita: "it",
  jpn: "jp",
  kan: "kn",
  kor: "ko",
  lav: "lv",
  lit: "lt",
  msa: "ms",
  mal: "ml",
  mar: "mr",
  nob: "nb",
  pol: "pl",
  // Brave requires a regioned Portuguese code; default to pt-br for a broader baseline.
  por: "pt-br",
  pan: "pa",
  ron: "ro",
  rus: "ru",
  srp: "sr",
  slk: "sk",
  slv: "sl",
  spa: "es",
  swe: "sv",
  tam: "ta",
  tel: "te",
  tha: "th",
  tur: "tr",
  ukr: "uk",
  vie: "vi",
};

export function inferBraveSearchLangFromFranc(code: string): BraveSearchLang | null {
  return FRANC_TO_BRAVE_SEARCH_LANG[code] ?? null;
}
